/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GgmlGlobal */

#ifndef _Included_GgmlGlobal
#define _Included_GgmlGlobal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GgmlGlobal
 * Method:    f
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GgmlGlobal_test
  (JNIEnv *, jclass);

/*
 * Class:     GgmlGlobal
 * Method:    newTensor1d
 * Signature: (LGgmlContext;LGgmlType;J)LGgmlTensor;
 */
JNIEXPORT jobject JNICALL Java_GgmlGlobal_newTensor1d
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     GgmlGlobal
 * Method:    newTensor2d
 * Signature: (LGgmlContext;LGgmlType;JJ)LGgmlTensor;
 */
JNIEXPORT jobject JNICALL Java_GgmlGlobal_newTensor2d
  (JNIEnv *, jclass, jobject, jint, jlong, jlong);

/*
 * Class:     GgmlGlobal
 * Method:    newTensor3d
 * Signature: (LGgmlContext;LGgmlType;JJJ)LGgmlTensor;
 */
JNIEXPORT jobject JNICALL Java_GgmlGlobal_newTensor3d
  (JNIEnv *, jclass, jobject, jint, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
